// Auto-generated. Daily scheduled task refreshes this file.
window.DASHBOARD_DATA = {
  "meta": {
    "lastUpdated": "2026-04-17T16:00:00-04:00",
    "marketSnapshot": {
      "sp500": 7013,
      "sp500WeekChange": 4.5,
      "ust10y": 4.2,
      "vix": 17.4,
      "note": "S&P 500 broke the 7,000 mark this week after a volatile Q1 — best weekly gain since May 2025."
    },
    "runHistory": [],
    "version": 1
  },
  "stocks": [
    {
      "ticker": "NVDA",
      "name": "NVIDIA Corp.",
      "sector": "AI / Semis",
      "price": 200.68,
      "ytd": -2.1,
      "target": 264.54,
      "pe": 40.5,
      "mcap": 4960,
      "rating": "Strong Buy",
      "revGrowth": "+73% YoY",
      "w52": "115.00 – 223.30",
      "thesis": "Dominant AI-accelerator franchise. Revenue grew <strong>+73% YoY</strong> with management guiding <strong>+77%</strong> next quarter. Datacenter TAM seen reaching $3–4T annual spend by 2030.",
      "catalysts": "Blackwell Ultra ramp · Rubin architecture disclosures · hyperscaler capex guides."
    },
    {
      "ticker": "MSFT",
      "name": "Microsoft Corp.",
      "sector": "Software / Cloud",
      "price": 424.83,
      "ytd": -3.4,
      "target": 584.24,
      "pe": 32.0,
      "mcap": 3170,
      "rating": "Strong Buy",
      "revGrowth": "+15% YoY",
      "w52": "355.67 – 555.45",
      "thesis": "Azure growing <strong>+39% YoY</strong> with <strong>$625B commercial RPO</strong>. Copilot monetisation ramping. Margin expansion room not yet in consensus per Morgan Stanley / Goldman.",
      "catalysts": "Q3 FY26 earnings (Apr 29) · Azure growth print · Copilot seat disclosures."
    },
    {
      "ticker": "AVGO",
      "name": "Broadcom Inc.",
      "sector": "AI / Semis",
      "price": 402.47,
      "ytd": 8.4,
      "target": 474.13,
      "pe": 38.5,
      "mcap": 1910,
      "rating": "Strong Buy",
      "revGrowth": "+22% YoY",
      "w52": "161.61 – 414.61",
      "thesis": "Custom silicon (XPU) + networking franchise serving hyperscalers. VMware cross-sell driving software mix. Structural winner in AI-interconnect.",
      "catalysts": "Hyperscaler ASIC wins · VMware ARR · Tomahawk 6 networking ramp."
    },
    {
      "ticker": "AMZN",
      "name": "Amazon.com Inc.",
      "sector": "Cloud / Consumer",
      "price": 249.7,
      "ytd": -9.2,
      "target": 281.16,
      "pe": 33.0,
      "mcap": 2620,
      "rating": "Strong Buy",
      "revGrowth": "+11% YoY",
      "w52": "185.00 – 265.40",
      "thesis": "AWS reaccelerating — <strong>+24% Q4'25</strong> with <strong>$57B backlog add</strong>. $200B FY26 capex for AI infra. Retail margins improving; ads compounding.",
      "catalysts": "Q1 earnings (May 1) · AWS growth cadence · AI services revenue."
    },
    {
      "ticker": "GOOGL",
      "name": "Alphabet Inc.",
      "sector": "Software / AI",
      "price": 205.4,
      "ytd": -1.8,
      "target": 245.0,
      "pe": 24.5,
      "mcap": 2530,
      "rating": "Strong Buy",
      "revGrowth": "+13% YoY",
      "w52": "148.20 – 225.60",
      "thesis": "Google Cloud growing mid-30s%. Gemini 2.0 + AI Overviews defending search. YouTube ads + subscription compounding. Waymo quietly scaling. Cheap vs Mag-7 peers.",
      "catalysts": "Q1 earnings (Apr 24) · Cloud growth · antitrust remedy ruling · Gemini 3."
    },
    {
      "ticker": "META",
      "name": "Meta Platforms",
      "sector": "Software / AI",
      "price": 720.5,
      "ytd": 6.1,
      "target": 825.0,
      "pe": 28.0,
      "mcap": 1830,
      "rating": "Strong Buy",
      "revGrowth": "+18% YoY",
      "w52": "445.00 – 758.00",
      "thesis": "Ad revenue reaccelerating from AI ranking gains. Llama 4 open-weight strategy expanding reach. Reality Labs losses stabilising. Ray-Ban smart glasses inflecting.",
      "catalysts": "Q1 earnings (Apr 30) · ad pricing · Llama 4 multimodal · Meta AI MAU."
    },
    {
      "ticker": "AAPL",
      "name": "Apple Inc.",
      "sector": "Consumer Tech",
      "price": 270.61,
      "ytd": 2.3,
      "target": 295.0,
      "pe": 34.5,
      "mcap": 4060,
      "rating": "Buy",
      "revGrowth": "+6% YoY",
      "w52": "188.00 – 275.30",
      "thesis": "Services now ~28% of revenue at 70%+ margins. iPhone 17 Pro refresh cycle +Apple Intelligence rollout supports units. Capital return program continues.",
      "catalysts": "Q2 FY26 earnings (May 1) · services growth · China iPhone sell-through."
    },
    {
      "ticker": "TSM",
      "name": "Taiwan Semiconductor",
      "sector": "AI / Semis",
      "price": 380.0,
      "ytd": 19.0,
      "target": 430.65,
      "pe": 28.0,
      "mcap": 1970,
      "rating": "Strong Buy",
      "revGrowth": "+41% YoY",
      "w52": "185.00 – 395.00",
      "thesis": "Raised FY26 USD revenue growth guide to <strong>&gt;30%</strong>. Q1 revenue +40.6% YoY. Sole-source for NVDA, AMD, AAPL leading-edge nodes. Capex at $52–56B.",
      "catalysts": "Monthly sales · 2nm node ramp · Arizona fab milestones · CoWoS capacity."
    },
    {
      "ticker": "AMD",
      "name": "Advanced Micro Devices",
      "sector": "AI / Semis",
      "price": 296.8,
      "ytd": 14.3,
      "target": 320.0,
      "pe": 45.0,
      "mcap": 482,
      "rating": "Buy",
      "revGrowth": "+28% YoY",
      "w52": "115.00 – 308.00",
      "thesis": "MI350 ramp with hyperscaler wins. France AI sovereign deal + server CPU share take. Valuation full but earnings trajectory improving.",
      "catalysts": "Q1 earnings (May 6) · MI400 disclosures · server CPU share."
    },
    {
      "ticker": "MU",
      "name": "Micron Technology",
      "sector": "AI / Semis",
      "price": 165.2,
      "ytd": 12.8,
      "target": 195.0,
      "pe": 18.0,
      "mcap": 185,
      "rating": "Buy",
      "revGrowth": "+55% YoY",
      "w52": "82.00 – 175.00",
      "thesis": "HBM3E/HBM4 sold out through 2026. DRAM pricing still tight; NAND stabilising. Cyclical with secular AI-memory tailwind.",
      "catalysts": "HBM4 qualification · DRAM contract pricing · NAND recovery pace."
    },
    {
      "ticker": "ARM",
      "name": "Arm Holdings",
      "sector": "AI / Semis",
      "price": 175.0,
      "ytd": -8.5,
      "target": 195.0,
      "pe": 95.0,
      "mcap": 184,
      "rating": "Buy",
      "revGrowth": "+25% YoY",
      "w52": "98.00 – 198.00",
      "thesis": "Royalty model scales with AI compute. v9 + Neoverse mix-shift lifts per-chip royalty. Custom silicon proliferation a tailwind.",
      "catalysts": "Q4 FY26 earnings (May 7) · v9 adoption · hyperscaler ARM share."
    },
    {
      "ticker": "CRM",
      "name": "Salesforce",
      "sector": "Software",
      "price": 310.0,
      "ytd": -4.5,
      "target": 380.0,
      "pe": 28.0,
      "mcap": 298,
      "rating": "Strong Buy",
      "revGrowth": "+9% YoY",
      "w52": "238.00 – 368.00",
      "thesis": "Agentforce (AI agents) driving upsell. FCF compounding >20%. Margin expansion story with ongoing cost discipline.",
      "catalysts": "Q1 earnings (May 28) · Agentforce ARR · Data Cloud attach."
    },
    {
      "ticker": "ORCL",
      "name": "Oracle",
      "sector": "Software / Cloud",
      "price": 210.0,
      "ytd": 7.2,
      "target": 240.0,
      "pe": 29.0,
      "mcap": 588,
      "rating": "Strong Buy",
      "revGrowth": "+12% YoY",
      "w52": "135.00 – 225.00",
      "thesis": "OCI growing triple-digits. AI training workloads + Stargate exposure. RPO up sharply; multi-year revenue visibility.",
      "catalysts": "Q4 FY26 earnings (Jun 10) · OCI growth · capex cadence."
    },
    {
      "ticker": "SNOW",
      "name": "Snowflake",
      "sector": "Data / AI",
      "price": 185.0,
      "ytd": -6.0,
      "target": 220.0,
      "pe": 0,
      "mcap": 62,
      "rating": "Buy",
      "revGrowth": "+27% YoY",
      "w52": "125.00 – 215.00",
      "thesis": "Product revenue growing high-20s. Cortex AI workloads inflecting. NRR stabilising around 125%. FCF margin expanding.",
      "catalysts": "Q1 earnings (May 21) · Cortex AI ARR · consumption guide."
    },
    {
      "ticker": "CRWD",
      "name": "CrowdStrike",
      "sector": "Cybersecurity",
      "price": 420.0,
      "ytd": 3.5,
      "target": 475.0,
      "pe": 85.0,
      "mcap": 105,
      "rating": "Strong Buy",
      "revGrowth": "+22% YoY",
      "w52": "255.00 – 460.00",
      "thesis": "Falcon platform consolidation continues. Charlotte AI driving SOC automation. Net retention >120%. July 2024 outage fully in the rearview.",
      "catalysts": "Q1 earnings (Jun 4) · module attach · Next-Gen SIEM ARR."
    },
    {
      "ticker": "PANW",
      "name": "Palo Alto Networks",
      "sector": "Cybersecurity",
      "price": 167.34,
      "ytd": -4.6,
      "target": 215.97,
      "pe": 52.0,
      "mcap": 110,
      "rating": "Buy",
      "revGrowth": "+15% YoY",
      "w52": "143.00 – 208.40",
      "thesis": "Platformization strategy driving ARR consolidation. Leading position in AI-native SOC (XSIAM). Morgan Stanley top cybersecurity pick.",
      "catalysts": "Q3 earnings (May 20) · NGS ARR growth · XSIAM deal size."
    },
    {
      "ticker": "NET",
      "name": "Cloudflare",
      "sector": "Cybersecurity / Infra",
      "price": 135.0,
      "ytd": -5.2,
      "target": 155.0,
      "pe": 0,
      "mcap": 47,
      "rating": "Buy",
      "revGrowth": "+28% YoY",
      "w52": "78.00 – 160.00",
      "thesis": "Workers AI + edge inference scaling. Enterprise large-deal traction accelerating. Mizuho top software pick with >$500K deal growth.",
      "catalysts": "Q1 earnings (May 7) · Workers AI revenue · large deal count."
    },
    {
      "ticker": "ZS",
      "name": "Zscaler",
      "sector": "Cybersecurity",
      "price": 230.0,
      "ytd": -1.8,
      "target": 270.0,
      "pe": 75.0,
      "mcap": 36,
      "rating": "Buy",
      "revGrowth": "+22% YoY",
      "w52": "170.00 – 255.00",
      "thesis": "Zero-Trust Exchange scaling with SASE adoption. ARR past $2.8B. FCF margin expanding toward 25%+.",
      "catalysts": "Q3 FY26 earnings (May 28) · ARR growth · FedRAMP High wins."
    },
    {
      "ticker": "NOW",
      "name": "ServiceNow Inc.",
      "sector": "Software",
      "price": 96.84,
      "ytd": -18.6,
      "target": 173.46,
      "pe": 40.0,
      "mcap": 101,
      "rating": "Strong Buy",
      "revGrowth": "+22% YoY",
      "w52": "85.00 – 121.80",
      "thesis": "Workflow leader with AI-agent layer (Now Assist). Sector valuation <strong>~40% below 3-yr avg</strong> per Mizuho — compelling risk/reward.",
      "catalysts": "Q1 earnings (Apr 23) · Now Assist ARR · federal pipeline."
    },
    {
      "ticker": "DDOG",
      "name": "Datadog",
      "sector": "Software / Observability",
      "price": 155.0,
      "ytd": 4.2,
      "target": 185.0,
      "pe": 72.0,
      "mcap": 53,
      "rating": "Buy",
      "revGrowth": "+25% YoY",
      "w52": "105.00 – 175.00",
      "thesis": "AI-native customers now ~12% of ARR. Platform expansion into security + LLM observability. NRR rebounding.",
      "catalysts": "Q1 earnings (May 6) · AI customer cohort · LLM observability ARR."
    },
    {
      "ticker": "JPM",
      "name": "JPMorgan Chase",
      "sector": "Financials",
      "price": 297.4,
      "ytd": 2.1,
      "target": 330.53,
      "pe": 13.8,
      "mcap": 830,
      "rating": "Buy",
      "revGrowth": "+8% YoY",
      "w52": "230.15 – 318.90",
      "thesis": "Q1 EPS <strong>$5.94 beat $5.46</strong> on IB + trading strength. Fortress balance sheet, 2.2% yield, benefits from healthy credit cycle.",
      "catalysts": "Q2 earnings (Jul 15) · NII trajectory · Basel III endgame · buybacks."
    },
    {
      "ticker": "BAC",
      "name": "Bank of America",
      "sector": "Financials",
      "price": 48.0,
      "ytd": 0.8,
      "target": 54.0,
      "pe": 13.2,
      "mcap": 370,
      "rating": "Buy",
      "revGrowth": "+6% YoY",
      "w52": "36.50 – 52.30",
      "thesis": "Q1 EPS $1.11 beat $1.00. Trading revenue up 12% (16th straight quarter of trading gains). NII ramping.",
      "catalysts": "Q2 earnings (Jul 16) · NII growth · deposit mix · consumer credit."
    },
    {
      "ticker": "V",
      "name": "Visa Inc.",
      "sector": "Financials / Payments",
      "price": 350.0,
      "ytd": 3.4,
      "target": 395.0,
      "pe": 29.5,
      "mcap": 680,
      "rating": "Strong Buy",
      "revGrowth": "+10% YoY",
      "w52": "265.00 – 372.00",
      "thesis": "Cross-border volume recovering; value-added services compounding. Exceptional FCF conversion; consistent buybacks.",
      "catalysts": "Q2 FY26 earnings (Apr 28) · cross-border volumes · VAS mix."
    },
    {
      "ticker": "MA",
      "name": "Mastercard",
      "sector": "Financials / Payments",
      "price": 545.0,
      "ytd": 2.5,
      "target": 605.0,
      "pe": 34.0,
      "mcap": 500,
      "rating": "Strong Buy",
      "revGrowth": "+11% YoY",
      "w52": "405.00 – 580.00",
      "thesis": "B2B + cyber/intel services driving growth premium vs V. Incremental margins remain high.",
      "catalysts": "Q1 earnings (Apr 30) · cross-border · services revenue."
    },
    {
      "ticker": "BLK",
      "name": "BlackRock",
      "sector": "Financials / Asset Mgmt",
      "price": 1125.0,
      "ytd": 4.8,
      "target": 1250.0,
      "pe": 23.0,
      "mcap": 170,
      "rating": "Buy",
      "revGrowth": "+12% YoY",
      "w52": "830.00 – 1180.00",
      "thesis": "Q1 EPS $12.53 beat $11.48. Record AUM; private markets integration post GIP/HPS. ETF flows dominant.",
      "catalysts": "Private markets fee ramp · ETF flows · Aladdin attach."
    },
    {
      "ticker": "GS",
      "name": "Goldman Sachs",
      "sector": "Financials / IB",
      "price": 615.0,
      "ytd": 6.0,
      "target": 680.0,
      "pe": 14.0,
      "mcap": 200,
      "rating": "Buy",
      "revGrowth": "+15% YoY",
      "w52": "410.00 – 655.00",
      "thesis": "M&A + ECM reopening. Wealth management franchise growing. Return-on-equity trajectory back above 13%.",
      "catalysts": "Q2 earnings (Jul 15) · IB backlog · ROE trajectory."
    },
    {
      "ticker": "VLO",
      "name": "Valero Energy",
      "sector": "Energy",
      "price": 223.64,
      "ytd": 38.7,
      "target": 221.59,
      "pe": 11.1,
      "mcap": 70,
      "rating": "Buy",
      "revGrowth": "+6% YoY",
      "w52": "121.00 – 239.00",
      "thesis": "Goldman's top refiner pick. Tight product markets, 2.0% dividend, <strong>fwd P/E of 11x</strong>. Highly cash-generative.",
      "catalysts": "Q1 earnings (Apr 24) · summer crack spreads · refinery utilisation."
    },
    {
      "ticker": "XOM",
      "name": "ExxonMobil",
      "sector": "Energy",
      "price": 122.0,
      "ytd": 9.5,
      "target": 135.0,
      "pe": 14.0,
      "mcap": 540,
      "rating": "Buy",
      "revGrowth": "+4% YoY",
      "w52": "98.00 – 128.00",
      "thesis": "Pioneer synergies ramping. Guyana production growth + LNG expansion. ~3.3% dividend yield.",
      "catalysts": "Q1 earnings (May 2) · Guyana production · Pioneer cost synergies."
    },
    {
      "ticker": "CVX",
      "name": "Chevron",
      "sector": "Energy",
      "price": 165.0,
      "ytd": 7.3,
      "target": 180.0,
      "pe": 13.0,
      "mcap": 298,
      "rating": "Buy",
      "revGrowth": "+3% YoY",
      "w52": "135.00 – 172.00",
      "thesis": "Hess close rekindling Guyana upside. TCO ramp underway. ~4.1% yield, consistent buybacks.",
      "catalysts": "Q1 earnings (May 2) · Hess integration · TCO ramp."
    },
    {
      "ticker": "MPC",
      "name": "Marathon Petroleum",
      "sector": "Energy",
      "price": 185.0,
      "ytd": 22.0,
      "target": 210.0,
      "pe": 11.0,
      "mcap": 60,
      "rating": "Buy",
      "revGrowth": "+5% YoY",
      "w52": "128.00 – 195.00",
      "thesis": "Goldman top refiner pick. Highest cap-return yield in group. Midstream MPLX stake accretive.",
      "catalysts": "Q1 earnings (May 6) · summer cracks · buyback cadence."
    },
    {
      "ticker": "CEG",
      "name": "Constellation Energy",
      "sector": "Utilities / AI Power",
      "price": 299.14,
      "ytd": -4.2,
      "target": 408.0,
      "pe": 32.0,
      "mcap": 107,
      "rating": "Buy",
      "revGrowth": "+10% YoY",
      "w52": "180.00 – 388.00",
      "thesis": "Nuclear fleet positioned for hyperscaler PPAs. 36% upside to consensus target. Guidance reset in April created entry point.",
      "catalysts": "Q1 earnings (May 7) · new PPA announcements · nuclear tax credits."
    },
    {
      "ticker": "LLY",
      "name": "Eli Lilly & Co.",
      "sector": "Healthcare / GLP-1",
      "price": 1022.02,
      "ytd": 5.8,
      "target": 1201.3,
      "pe": 44.8,
      "mcap": 970,
      "rating": "Buy",
      "revGrowth": "+32% YoY",
      "w52": "720.00 – 1070.00",
      "thesis": "Mounjaro/Zepbound GLP-1 still supply-constrained. <strong>FDA approved oral GLP-1 (Foundayo)</strong>. Orforglipron catalyst approaches.",
      "catalysts": "Q1 earnings (Apr 30) · Foundayo launch · orforglipron Ph3 CV data."
    },
    {
      "ticker": "UNH",
      "name": "UnitedHealth Group",
      "sector": "Healthcare",
      "price": 545.0,
      "ytd": -2.1,
      "target": 630.0,
      "pe": 18.8,
      "mcap": 500,
      "rating": "Buy",
      "revGrowth": "+8% YoY",
      "w52": "448.00 – 620.00",
      "thesis": "MLR stabilising; Optum Health + Rx compounding. Post-MA headline overhang fading. Reasonable entry vs history.",
      "catalysts": "Q1 earnings (Apr 17) · MLR trajectory · MA bids."
    },
    {
      "ticker": "NVO",
      "name": "Novo Nordisk",
      "sector": "Healthcare / GLP-1",
      "price": 98.0,
      "ytd": -3.5,
      "target": 125.0,
      "pe": 25.0,
      "mcap": 430,
      "rating": "Buy",
      "revGrowth": "+22% YoY",
      "w52": "75.00 – 112.00",
      "thesis": "Wegovy/Ozempic supply improving; pipeline includes amycretin, CagriSema. Trades at discount to LLY on GLP-1 franchise.",
      "catalysts": "Q1 earnings (May 7) · CagriSema Ph3 · amycretin data."
    },
    {
      "ticker": "ISRG",
      "name": "Intuitive Surgical",
      "sector": "Healthcare / MedTech",
      "price": 620.0,
      "ytd": 4.5,
      "target": 700.0,
      "pe": 72.0,
      "mcap": 220,
      "rating": "Strong Buy",
      "revGrowth": "+18% YoY",
      "w52": "440.00 – 655.00",
      "thesis": "da Vinci 5 ramp; procedure growth double-digits. Pristine recurring revenue mix. Expanded indications opening new TAM.",
      "catalysts": "Q1 earnings (Apr 22) · dv5 placements · procedure growth."
    },
    {
      "ticker": "ABBV",
      "name": "AbbVie",
      "sector": "Pharma",
      "price": 220.0,
      "ytd": 5.2,
      "target": 245.0,
      "pe": 16.0,
      "mcap": 390,
      "rating": "Buy",
      "revGrowth": "+7% YoY",
      "w52": "170.00 – 230.00",
      "thesis": "Skyrizi + Rinvoq offsetting Humira erosion faster than expected. 2026 seen as trough year with growth reaccelerating into 2027.",
      "catalysts": "Q1 earnings (Apr 25) · Skyrizi/Rinvoq scripts · post-Humira trajectory."
    },
    {
      "ticker": "TMO",
      "name": "Thermo Fisher Scientific",
      "sector": "Healthcare / Life Sci",
      "price": 560.0,
      "ytd": 1.8,
      "target": 640.0,
      "pe": 25.0,
      "mcap": 215,
      "rating": "Buy",
      "revGrowth": "+5% YoY",
      "w52": "445.00 – 595.00",
      "thesis": "Biopharma capex bottoming. Pharma services backlog rebuilding. PPI pricing engine intact.",
      "catalysts": "Q1 earnings (Apr 23) · biopharma order trends · pharma services growth."
    },
    {
      "ticker": "COST",
      "name": "Costco Wholesale",
      "sector": "Consumer Staples",
      "price": 1010.79,
      "ytd": -2.8,
      "target": 1078.0,
      "pe": 48.0,
      "mcap": 449,
      "rating": "Buy",
      "revGrowth": "+8% YoY",
      "w52": "820.00 – 1078.20",
      "thesis": "Membership income <strong>+13.6%</strong> YoY, traffic +3.0%, ticket +4.8%. Defensive compounder with exceptional pricing power.",
      "catalysts": "April sales report · membership fee comps · special dividend."
    },
    {
      "ticker": "WMT",
      "name": "Walmart",
      "sector": "Consumer Staples",
      "price": 110.0,
      "ytd": 1.2,
      "target": 125.0,
      "pe": 37.5,
      "mcap": 880,
      "rating": "Buy",
      "revGrowth": "+5% YoY",
      "w52": "82.00 – 116.00",
      "thesis": "Advertising + Marketplace + Walmart+ driving mix-shift to higher margins. Automation capex scaling.",
      "catalysts": "Q1 earnings (May 15) · ad revenue · e-commerce profitability."
    },
    {
      "ticker": "PG",
      "name": "Procter & Gamble",
      "sector": "Consumer Staples",
      "price": 172.0,
      "ytd": 2.4,
      "target": 185.0,
      "pe": 25.0,
      "mcap": 400,
      "rating": "Buy",
      "revGrowth": "+4% YoY",
      "w52": "148.00 – 180.00",
      "thesis": "Pricing holding; volumes inflecting positive. China stabilising. FX becoming a tailwind. Dividend aristocrat at 2.4% yield.",
      "catalysts": "Q3 FY26 earnings (Apr 23) · volume growth · China trajectory."
    },
    {
      "ticker": "HD",
      "name": "Home Depot",
      "sector": "Consumer Discretionary",
      "price": 415.0,
      "ytd": 3.8,
      "target": 460.0,
      "pe": 25.5,
      "mcap": 412,
      "rating": "Buy",
      "revGrowth": "+5% YoY",
      "w52": "335.00 – 440.00",
      "thesis": "Pro customer growth accelerating post-SRS Distribution. Housing turnover stabilising. Long-tenured management.",
      "catalysts": "Q1 earnings (May 20) · comps · pro segment growth."
    },
    {
      "ticker": "NKE",
      "name": "Nike",
      "sector": "Consumer Discretionary",
      "price": 82.0,
      "ytd": -6.5,
      "target": 95.0,
      "pe": 30.0,
      "mcap": 122,
      "rating": "Hold",
      "revGrowth": "-3% YoY",
      "w52": "68.00 – 95.00",
      "thesis": "Turnaround under new CEO (Elliott Hill). Product pipeline resetting; wholesale re-engagement. Risk/reward improving but still early innings.",
      "catalysts": "Q4 FY26 earnings (Jun 25) · DTC/wholesale mix · China recovery."
    },
    {
      "ticker": "MCD",
      "name": "McDonald's",
      "sector": "Consumer Discretionary",
      "price": 330.0,
      "ytd": 4.3,
      "target": 355.0,
      "pe": 25.0,
      "mcap": 235,
      "rating": "Buy",
      "revGrowth": "+4% YoY",
      "w52": "260.00 – 345.00",
      "thesis": "Value menu reviving traffic. Delivery + loyalty program scaling. International comps improving.",
      "catalysts": "Q1 earnings (Apr 29) · US comps · value platform traction."
    },
    {
      "ticker": "SBUX",
      "name": "Starbucks",
      "sector": "Consumer Discretionary",
      "price": 98.0,
      "ytd": 5.6,
      "target": 115.0,
      "pe": 26.0,
      "mcap": 111,
      "rating": "Buy",
      "revGrowth": "+2% YoY",
      "w52": "72.00 – 108.00",
      "thesis": "Back-to-Starbucks turnaround under Niccol showing early signs. Menu simplification + service speed investments.",
      "catalysts": "Q2 FY26 earnings (Apr 29) · US traffic · China strategy update."
    },
    {
      "ticker": "CAT",
      "name": "Caterpillar",
      "sector": "Industrials",
      "price": 390.0,
      "ytd": 2.1,
      "target": 425.0,
      "pe": 17.0,
      "mcap": 185,
      "rating": "Buy",
      "revGrowth": "+3% YoY",
      "w52": "295.00 – 418.00",
      "thesis": "Data center power gensets + mining + construction cycles converging. Backlog at record levels.",
      "catalysts": "Q1 earnings (Apr 30) · backlog · data center orders."
    },
    {
      "ticker": "GE",
      "name": "GE Aerospace",
      "sector": "Industrials / Aerospace",
      "price": 245.0,
      "ytd": 4.7,
      "target": 285.0,
      "pe": 35.0,
      "mcap": 260,
      "rating": "Strong Buy",
      "revGrowth": "+12% YoY",
      "w52": "165.00 – 260.00",
      "thesis": "Aftermarket services on installed engine base compound. LEAP maturation; air traffic growth supportive.",
      "catalysts": "Q1 earnings (Apr 22) · services growth · LEAP deliveries."
    },
    {
      "ticker": "HON",
      "name": "Honeywell",
      "sector": "Industrials",
      "price": 225.0,
      "ytd": 3.1,
      "target": 250.0,
      "pe": 22.0,
      "mcap": 145,
      "rating": "Buy",
      "revGrowth": "+4% YoY",
      "w52": "185.00 – 238.00",
      "thesis": "Portfolio split into three standalone companies unlocking sum-of-parts value. Aerospace + automation remain strong.",
      "catalysts": "Portfolio separation progress · Q1 earnings (Apr 24) · aerospace growth."
    },
    {
      "ticker": "VST",
      "name": "Vistra Corp.",
      "sector": "Utilities / AI Power",
      "price": 165.53,
      "ytd": 3.2,
      "target": 195.0,
      "pe": 22.0,
      "mcap": 56,
      "rating": "Buy",
      "revGrowth": "+12% YoY",
      "w52": "88.00 – 185.00",
      "thesis": "Nuclear + gas fleet best-positioned for Texas AI data center demand. New Chief AI & Digital Officer signals growth focus.",
      "catalysts": "Q1 earnings (May 7) · data center PPAs · Comanche Peak outlook."
    },
    {
      "ticker": "NEE",
      "name": "NextEra Energy",
      "sector": "Utilities",
      "price": 72.0,
      "ytd": 2.9,
      "target": 85.0,
      "pe": 22.0,
      "mcap": 148,
      "rating": "Buy",
      "revGrowth": "+7% YoY",
      "w52": "58.00 – 78.00",
      "thesis": "Largest renewable developer + FPL regulated utility. AI power demand creating long-dated renewable PPAs.",
      "catalysts": "Q1 earnings (Apr 23) · renewables backlog · FPL rate case."
    },
    {
      "ticker": "LIN",
      "name": "Linde plc",
      "sector": "Materials",
      "price": 475.0,
      "ytd": 1.8,
      "target": 520.0,
      "pe": 30.0,
      "mcap": 225,
      "rating": "Buy",
      "revGrowth": "+5% YoY",
      "w52": "400.00 – 495.00",
      "thesis": "Industrial gas duopoly with project backlog at record levels. Clean hydrogen + semiconductor exposure compounding.",
      "catalysts": "Q1 earnings (May 1) · project backlog · hydrogen wins."
    }
  ]
};
